//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Button
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Button()
        {
            this.ButtonAccesses = new HashSet<ButtonAccess>();
        }
    
        public decimal ButtonID { get; set; }
        public string ButtonName { get; set; }
        public string ButtonDesc { get; set; }
        public string ButtonArabicDesc { get; set; }
        public Nullable<bool> IsVisable { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ButtonAccess> ButtonAccesses { get; set; }
    }
}
