//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangelInfo
    {
        public decimal DangelID { get; set; }
        public string DangelPass { get; set; }
        public string DangelSerial { get; set; }
        public string ConnectingDevice { get; set; }
        public string SoftwareVersion { get; set; }
        public string Country { get; set; }
        public string Maxprivilege { get; set; }
        public string ExpireDate { get; set; }
        public string Sump { get; set; }
        public string LSBCode { get; set; }
        public Nullable<decimal> ProvinceID { get; set; }
    }
}
