//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public decimal LocationID { get; set; }
        public Nullable<decimal> PlainID { get; set; }
        public Nullable<decimal> CatchmentID { get; set; }
        public Nullable<decimal> AreaID { get; set; }
        public decimal CityID { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Catchment Catchment { get; set; }
        public virtual City City { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Plain Plain { get; set; }
    }
}
