//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBISToReport
    {
        public decimal ReportID { get; set; }
        public decimal OBISID { get; set; }
        public Nullable<decimal> SheetID { get; set; }
        public Nullable<decimal> OBISTypeID { get; set; }
    
        public virtual OBISS OBISS { get; set; }
        public virtual Report Report { get; set; }
    }
}
