//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class regulationRule
    {
        public decimal regulationRuleID { get; set; }
        public decimal OBISUnitID { get; set; }
        public decimal UnitIDForshow { get; set; }
        public string regulationRule1 { get; set; }
    }
}
