//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE1
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempSaba
    {
        public decimal MeterID { get; set; }
        public string MeterNumber { get; set; }
        public string ReadDate { get; set; }
        public Nullable<int> classID { get; set; }
        public string s0 { get; set; }
        public string s1 { get; set; }
        public string s2 { get; set; }
        public string s3 { get; set; }
        public string s4 { get; set; }
        public string s5 { get; set; }
        public string s6 { get; set; }
        public string s7 { get; set; }
        public string s8 { get; set; }
        public string s9 { get; set; }
        public string s10 { get; set; }
        public string s11 { get; set; }
        public string s12 { get; set; }
        public string s13 { get; set; }
        public string s14 { get; set; }
        public string s15 { get; set; }
        public string s16 { get; set; }
        public string s17 { get; set; }
        public string s18 { get; set; }
        public string s19 { get; set; }
        public string s20 { get; set; }
        public string s21 { get; set; }
        public string s22 { get; set; }
        public string s23 { get; set; }
        public string ErrorMessage { get; set; }
    }
}
