//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardToMeter
    {
        public decimal CardID { get; set; }
        public decimal MeterID { get; set; }
        public string SetDate { get; set; }
        public decimal UserID { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual Meter Meter { get; set; }
    }
}
