//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreateTokenByDongle
    {
        public decimal TokenFromDongleID { get; set; }
        public int CurrentYear { get; set; }
        public int DayNumber { get; set; }
        public int MinuteOfDay { get; set; }
        public decimal SystemID { get; set; }
        public int SequenceNumber { get; set; }
        public string TokenID { get; set; }
        public decimal MeterID { get; set; }
    }
}
