//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Meters = new HashSet<Meter>();
        }
    
        public decimal CustomerID { get; set; }
        public string CustomerName { get; set; }
        public string Customerfamily { get; set; }
        public string CustomerTel { get; set; }
        public string CustomerAddress { get; set; }
        public string WatersubscriptionNumber { get; set; }
        public string ElecsubscriptionNumber { get; set; }
        public Nullable<decimal> LocationID { get; set; }
        public Nullable<decimal> NationalCode { get; set; }
        public string MobileNumber { get; set; }
        public string Longitude { get; set; }
        public string Latitude { get; set; }
        public string PostCode { get; set; }
        public Nullable<decimal> officeID { get; set; }
        public string DossierNumber { get; set; }
        public string Flowindossier { get; set; }
        public string Diameterofpipe { get; set; }
        public string Welldepth { get; set; }
        public string WellLicense { get; set; }
        public string WellAddress { get; set; }
        public string FatherName { get; set; }
        public Nullable<decimal> EofficeID { get; set; }
        public Nullable<decimal> WSubofficeID { get; set; }
        public Nullable<decimal> ESubofficeID { get; set; }
        public Nullable<int> TypeOfUse { get; set; }
    
        public virtual EOffice EOffice { get; set; }
        public virtual ESubOffice ESubOffice { get; set; }
        public virtual Location Location { get; set; }
        public virtual Office Office { get; set; }
        public virtual SubOffice SubOffice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meter> Meters { get; set; }
    }
}
