//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MessageText
    {
        public decimal MessageTextID { get; set; }
        public int MessageID { get; set; }
        public string MessageText1 { get; set; }
        public int LanguageID { get; set; }
        public string foruseIn { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
