//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meter
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Meter()
        {
            this.Curves = new HashSet<Curve>();
            this.CardToMeters = new HashSet<CardToMeter>();
            this.ConsumedWaters = new HashSet<ConsumedWater>();
            this.MeterErrors = new HashSet<MeterError>();
            this.MeterToGroups = new HashSet<MeterToGroup>();
            this.Tokens = new HashSet<Token>();
            this.TokenFromDangles = new HashSet<TokenFromDangle>();
        }
    
        public decimal MeterID { get; set; }
        public string MeterNumber { get; set; }
        public Nullable<decimal> DeviceModelID { get; set; }
        public Nullable<bool> IsDirect { get; set; }
        public Nullable<decimal> SoftversionToDeviceModelID { get; set; }
        public Nullable<decimal> ModemID { get; set; }
        public Nullable<bool> Valid { get; set; }
        public Nullable<decimal> CustomerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curve> Curves { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual DeviceModel DeviceModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CardToMeter> CardToMeters { get; set; }
        public virtual ConsumedActiveEnergy ConsumedActiveEnergy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConsumedWater> ConsumedWaters { get; set; }
        public virtual Modem Modem { get; set; }
        public virtual SoftversionToDeviceModel SoftversionToDeviceModel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterError> MeterErrors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MeterToGroup> MeterToGroups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Token> Tokens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TokenFromDangle> TokenFromDangles { get; set; }
    }
}
