//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeterError
    {
        public decimal MeterErrorID { get; set; }
        public decimal OBISValueHeaderID { get; set; }
        public decimal ErrorID { get; set; }
        public decimal MeterID { get; set; }
        public int Value { get; set; }
    
        public virtual Error Error { get; set; }
        public virtual Meter Meter { get; set; }
    }
}
