//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBISValueHeader
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBISValueHeader()
        {
            this.Curves = new HashSet<Curve>();
            this.OBISValueDetails = new HashSet<OBISValueDetail>();
        }
    
        public decimal OBISValueHeaderID { get; set; }
        public string ReadDate { get; set; }
        public decimal DeviceTypeID { get; set; }
        public decimal UserID { get; set; }
        public string TransferDate { get; set; }
        public decimal MeterID { get; set; }
        public decimal SourceTypeID { get; set; }
        public Nullable<bool> valid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curve> Curves { get; set; }
        public virtual DeviceType DeviceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OBISValueDetail> OBISValueDetails { get; set; }
        public virtual SourceType SourceType { get; set; }
        public virtual User User { get; set; }
    }
}
