//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusOBISsDesc
    {
        public decimal OBISID { get; set; }
        public int BitNumber { get; set; }
        public string FarsiDescForTrue { get; set; }
        public string LatinDescForTrue { get; set; }
        public string FarsiDescForFalse { get; set; }
        public string LatinDescForFalse { get; set; }
    
        public virtual OldOBISs OldOBISs { get; set; }
    }
}
