//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SabaVEE2
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempMeter1
    {
        public decimal MeterID { get; set; }
        public string MeterNumber { get; set; }
        public string software { get; set; }
        public decimal OBISValueHeaderID { get; set; }
    }
}
